### PR TITLE
Try to the fix the discrepency issue between the two names.

### PR DESCRIPTION
**Pull request by cheginit**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by cheginit** [comment]
@conda-forge-admin, please rerender

**Comment by cheginit** [comment]
@manujosephv I noticed that you've added `entmax` as a hard dependency. Unfortunately, this package is not available on `conda-forge` and seems to be unmaintained. Since the package has a permissive license (MIT), is there a way for you to use parts of their code that you need so `pytorch-tabular` don't have to have `entmax` as a dependency?

**Comment by cheginit** [comment]
BTW, this PR will resolve the issue with the package not being available for Windows!

**Comment by manujosephv** [comment]
Awesome!! 

And about the entmax.. I recently factored out that code to that library.. I can add that back.. But is that a blocker for conda installation?

**Comment by cheginit** [comment]
Ah. Ok. That's great if it's not a dependency. In the current official version, pytorch-tabular does not depend on entmax, but when I was searching the main branch a couple of days ago, I noticed that you're importing entmax in the layers module and have added it as a dependency to requirements.txt. Can you please confirm that it's not the case anymore? Since entmax is not on conda-forge, if the next release of pytorch-tabular depends on, we cannot update pytorch-tabular on conda-forget to the next release.

**Comment by manujosephv** [comment]
ah!.. currently entmax is a dependency... But I get the issue. I'll incude the code directly in the repo and avoid the entmax dependency. I've added  `captum` as a dependency as well, is that going to be a problem? 
I'm planning a release soon, with a lot of new features..

**Comment by cheginit** [comment]
No, using [`captum`](https://anaconda.org/conda-forge/captum) is fine since it's available on `conda-forge`.

Great, looking forward to the new release. Keep up the good work!

**Pull request merged**
